import { createBlock } from '@covbot/vite-plugin-github-block/client';
import { react, useBlockContext } from '@covbot/vite-plugin-github-block/react';
import { FileBlockProps } from '@githubnext/blocks';
import { ThemeProvider, BaseStyles } from '@primer/react';
import { useMemo } from 'react';
import { CoverageTable } from '../components/CoverageTable';
import { getParsedCoverage } from '../utils/getParsedCoverage';

const CoverageBlock = () => {
	const { context, content, metadata, onUpdateMetadata } = useBlockContext() as FileBlockProps;

	const parsedCoverage = useMemo(() => getParsedCoverage(content, context.path), [content, context.path]);

	if (!parsedCoverage) {
		return <div>This file is not supported</div>;
	}

	return (
		<ThemeProvider>
			<BaseStyles>
				<CoverageTable coverage={parsedCoverage} />
			</BaseStyles>
		</ThemeProvider>
	);
};

export default createBlock({
	id: 'covbot.file-coverage-block',
	title: 'Jest coverage',
	matches: ['*'],
	description: 'Display coverage, generated by Jest.',
	type: 'file',
	render: react(CoverageBlock),
});
